name: Generate Breakout Game

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  breakout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate breakout SVG
        uses: cyprieng/github-breakout@v1.0.0
        with:
          github_username: anvnh                
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Commit and push result
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add *.svg
          git commit -m "Update breakout game SVG" || echo "No changes"
          git push
